// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvqeI41ySYFuksHVpjzDd7ZfDZikP5Q4',
    appId: '1:249137204258:web:490ebfb89ca0f2091ace7b',
    messagingSenderId: '249137204258',
    projectId: 'tts06c1',
    authDomain: 'tts06c1.firebaseapp.com',
    storageBucket: 'tts06c1.appspot.com',
    measurementId: 'G-WN3H5D1R1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc66t_DTZxPvYUroFCsVQ0U7lN8FN3TC0',
    appId: '1:249137204258:android:4cb321c96c0ebb011ace7b',
    messagingSenderId: '249137204258',
    projectId: 'tts06c1',
    storageBucket: 'tts06c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmiG7wz1QOU-4yiYsjgOcQUGK3Av87xfQ',
    appId: '1:249137204258:ios:4f41ac1e7aca16561ace7b',
    messagingSenderId: '249137204258',
    projectId: 'tts06c1',
    storageBucket: 'tts06c1.appspot.com',
    iosBundleId: 'com.example.firebasetts06c1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmiG7wz1QOU-4yiYsjgOcQUGK3Av87xfQ',
    appId: '1:249137204258:ios:68e13e37cc3f8f471ace7b',
    messagingSenderId: '249137204258',
    projectId: 'tts06c1',
    storageBucket: 'tts06c1.appspot.com',
    iosBundleId: 'com.example.firebasetts06c1.RunnerTests',
  );
}
